{% set name = "configparser" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/configparser-{{ version }}.tar.gz
  sha256: ec914ab1e56c672de1f5c3483964e68f71b34e457904b7b76e06b922aec067a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - pip
  run:
    - python >=3.8

test:
  imports:
    - configparser
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: Updated configparser from Python 3.8 for Python 2.6+.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
