{% set version = "4.0.1" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: 5e4c0d9de6ffc76f625eda1f5e28cec0700aed7cdacfe5070964df002ac02fec

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - backports
    - pip
    - python
    - setuptools_scm >=1.15.0
  run:
    - backports
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
