{% set version = "3.8.1" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: bc37850f0cc42a1725a796ef7d92690651bf1af37d744cc63161dac62cabee17

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - backports
    - pip
    - python
  run:
    - backports
    - python

test:
  imports:
    - backports
    - backports.configparser
    - configparser

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
