{% set version = "7.1.0" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: eb82646c892dbdf773dae19c633044d163c3129971ae09b49410a303b8e0a5f7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - backports
    - backports.configparser
    - configparser
  commands:
    - pip check

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: Updated configparser from Python 3.8 for Python 2.6+.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
