appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: BEpkOC2YmpxMJMIcpkP++o8OfNfqCk/VUWcaM4zzEqD9rrcDdemKS2xo5P7kSKuavV07alh4tee6RDJ5SqZ1NaF6SUiAxYLI6AoWk6K44QDJF8Jmzczkt06i1cY70Pv87FjpqrGecsIYSeTw1aBKa6LSOSMYXn5XMO1sHkWco9UBe/UGoB1DFFf36CyTPSlDGjhKaW/7KqAqKq6j+sTqxjAEJ2WZb+nlzq8PY69LN9gem27KvBNE7nyWAvleRUpWkRpnuypUqokUquqc6v5v7NEzPAzYZvNOD4uqB68Neb09fHuo5x09YJ/IrIgX8e7DD+rib7hheZMW6rM3s8w41tmPZmor4Twoin+hLZq33b3ZCxMILmP/QdKi9wveD2G6nJzBX+GpB745QgnUtPEE0TTfdTzmQKYtTjFVJ6DTL/VBi6CbQWbmul1QV2s+/lDoHwVv8qr2h7uza91FFm01K7JwgyvCLxHrG2PXE4fZ3SZTnOD8pEd3v7noJpnkXEK/AwIkey06KIIfLGfTaFgirUFf/6gaiTKcvZV5zcv0i69MCR1DkLAMyIC/H4N2ihoGucUeiCGTQo2oGemcJItfzlzAeQJ4A9DFKK23rtTV0ZQYbsQt2ZmWa+NcAVcvzS1qoOG2Esyp48rB6jGcd1HQf5S5awvo1AkaMswLpsTPpTg=}
